### ISSUE TITLE
1.17.0 final release checklist

### ISSUE THREAD

**Issue by nitzmahone** [python-cffi/cffi#105]
Now that Python 3.13.0rc1 has been tagged off, it's time to do a final release of 1.17 with support for 3.13.

* [x] Evaluate merged commits and open PRs since 1.17.0rc1 for cherry-pick - if any that affect runtime, we should do an rc2
* [x] Verify python_requires and other trove metadata
* [x] Update CI and tests to 3.13.0rc1 once available via cibuildwheel/manylinux/GHA (or use private copies)
* [x] Do final build and release.

**Comment by hugovk** [comment]
> * [ ]  Update CI and tests to 3.13.0rc1 once available via cibuildwheel/manylinux/GHA (or use private copies)

cibuildwheel 2.2.0 has now been released that builds 3.13.0rc1 wheels by default.

https://github.com/pypa/cibuildwheel/releases/tag/v2.20.0
